version: 2

jobs:
  init:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm i
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  version: 2
  build_release:
    jobs:
      - init
      - release:
          requires:
            - init
