version: 2.1

jobs:
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm i
      - run:
          name: release
          command: npm run semantic-release || true
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules


workflows:
  release:
    jobs:
      - init
      - release
